name = "monopolyq_theory"
version = "0.1.0"
keywords = ["math", "economics", "monopoly"]
defaultTargets = ["MonopolyqTheory"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "MonopolyqTheory"
